import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lenovo
 */
public class AplikasiCekCuacaSederhana extends javax.swing.JFrame {

    /**
     * Creates new form AplikasiCekCuacaSederhana
     */
    public AplikasiCekCuacaSederhana() {
        initComponents();
        
        DefaultTableModel model = (DefaultTableModel) tblDataCuaca.getModel();
    model.setColumnIdentifiers(new Object[]{"Kota", "Cuaca", "Suhu"});

    // Muat kota favorit dari file
    try {
        java.io.File file = new java.io.File("DataCuaca/kotaFavorit.txt");
        if (file.exists()) {
            BufferedReader reader = new BufferedReader(new FileReader(file));
            String line;
            while ((line = reader.readLine()) != null) {
                cmbPilihKota.addItem(line); // Tambahkan kota ke ComboBox
            }
            reader.close();
        }
    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "Gagal memuat daftar kota favorit: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmbPilihKota = new javax.swing.JComboBox<>();
        txtCariNamaKota = new javax.swing.JTextField();
        lblCuaca = new javax.swing.JLabel();
        lblSuhu = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnCekCuaca = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDataCuaca = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        btnMuatData = new javax.swing.JButton();
        btnPinKota = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(74, 98, 138));
        setForeground(new java.awt.Color(74, 98, 138));

        jPanel1.setBackground(new java.awt.Color(74, 98, 138));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(223, 242, 235));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Aplikasi Cek Cuaca");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(122, 178, 211));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Pilih Kota");

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cari Nama Kota");

        cmbPilihKota.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        cmbPilihKota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPilihKotaActionPerformed(evt);
            }
        });

        txtCariNamaKota.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        txtCariNamaKota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCariNamaKotaActionPerformed(evt);
            }
        });

        lblCuaca.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblCuaca.setForeground(new java.awt.Color(255, 255, 255));
        lblCuaca.setText("Cuaca : ");

        lblSuhu.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblSuhu.setForeground(new java.awt.Color(255, 255, 255));
        lblSuhu.setText("Suhu : ");

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Informasi Cuaca dan Suhu");

        btnCekCuaca.setBackground(new java.awt.Color(74, 98, 138));
        btnCekCuaca.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btnCekCuaca.setForeground(new java.awt.Color(255, 255, 255));
        btnCekCuaca.setText("Cek Cuaca");
        btnCekCuaca.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCekCuaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCekCuacaActionPerformed(evt);
            }
        });

        btnSimpan.setBackground(new java.awt.Color(74, 98, 138));
        btnSimpan.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setText("Simpan");
        btnSimpan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        tblDataCuaca.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        tblDataCuaca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblDataCuaca);

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tabel Data Cuaca");

        btnMuatData.setBackground(new java.awt.Color(74, 98, 138));
        btnMuatData.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btnMuatData.setForeground(new java.awt.Color(255, 255, 255));
        btnMuatData.setText("Tampilkan Data");
        btnMuatData.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMuatData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMuatDataActionPerformed(evt);
            }
        });

        btnPinKota.setBackground(new java.awt.Color(74, 98, 138));
        btnPinKota.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btnPinKota.setForeground(new java.awt.Color(255, 255, 255));
        btnPinKota.setText("Pin Kota");
        btnPinKota.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPinKota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPinKotaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPinKota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnCekCuaca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMuatData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblSuhu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCuaca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCariNamaKota)
                            .addComponent(cmbPilihKota, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbPilihKota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCariNamaKota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(btnCekCuaca, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPinKota, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCuaca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSuhu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMuatData, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbPilihKotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPilihKotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPilihKotaActionPerformed

    private void txtCariNamaKotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCariNamaKotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCariNamaKotaActionPerformed

    private void btnMuatDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMuatDataActionPerformed
    try {
        // Tentukan jalur folder dan file
        String folderPath = "DataCuaca"; // Nama folder
        String filePath = folderPath + "/dataCuaca.csv"; // File di dalam folder

        // Periksa apakah folder dan file ada
        java.io.File file = new java.io.File(filePath);
        if (!file.exists()) {
            JOptionPane.showMessageDialog(this, "File dataCuaca.csv tidak ditemukan di folder " + folderPath, "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Baca file
        BufferedReader reader = new BufferedReader(new FileReader(filePath));
        DefaultTableModel model = (DefaultTableModel) tblDataCuaca.getModel();
        model.setRowCount(0); // Hapus semua baris sebelumnya
        String line;
        while ((line = reader.readLine()) != null) {
            String[] data = line.split(",");
            model.addRow(data); // Tambahkan data ke tabel
        }
        reader.close();

        JOptionPane.showMessageDialog(this, "Data berhasil dimuat dari folder " + folderPath + "!");
    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "Gagal membaca file data cuaca: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }    // TODO add your handling code here:
    }//GEN-LAST:event_btnMuatDataActionPerformed

    private void btnCekCuacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCekCuacaActionPerformed
    String kota = txtCariNamaKota.getText();
    if (kota.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Masukkan nama kota terlebih dahulu!", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Array cuaca dan rentang suhu yang sesuai
    String[] cuacaArray = {"Cerah", "Hujan", "Berawan", "Gerimis", "Badai"};
    java.util.Random random = new java.util.Random();

    String cuacaRandom = cuacaArray[random.nextInt(cuacaArray.length)];
    String suhuRandom;

    // Tentukan rentang suhu berdasarkan cuaca
    switch (cuacaRandom) {
        case "Cerah":
            suhuRandom = (30 + random.nextInt(11)) + "°C"; // 30°C - 40°C
            break;
        case "Hujan":
            suhuRandom = (5 + random.nextInt(6)) + "°C"; // 5°C - 10°C
            break;
        case "Berawan":
            suhuRandom = (20 + random.nextInt(6)) + "°C"; // 20°C - 25°C
            break;
        case "Gerimis":
            suhuRandom = (15 + random.nextInt(6)) + "°C"; // 15°C - 20°C
            break;
        case "Badai":
            suhuRandom = (10 + random.nextInt(6)) + "°C"; // 10°C - 15°C
            break;
        default:
            suhuRandom = "N/A"; // Default, seharusnya tidak tercapai
    }

    // Set nilai pada label
    lblCuaca.setText("Cuaca : " + cuacaRandom);
    lblSuhu.setText("Suhu : " + suhuRandom);

    JOptionPane.showMessageDialog(this, "Cuaca berhasil diperbarui untuk kota: " + kota);        // TODO add your handling code here:
    }//GEN-LAST:event_btnCekCuacaActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
    try {
        // Tentukan jalur folder dan file
        String folderPath = "DataCuaca"; // Nama folder
        String filePath = folderPath + "/dataCuaca.csv"; // File di dalam folder

        // Buat folder jika belum ada
        java.io.File folder = new java.io.File(folderPath);
        if (!folder.exists()) {
            folder.mkdir(); // Buat folder
        }

        // Tulis data ke file
        try (FileWriter writer = new FileWriter(filePath, true)) { // 'true' untuk append
            writer.append(txtCariNamaKota.getText() + "," + lblCuaca.getText() + "," + lblSuhu.getText() + "\n");
            JOptionPane.showMessageDialog(this, "Data cuaca berhasil disimpan ke folder " + folderPath + "!");
        }
    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "Gagal menyimpan data: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }    // TODO add your handling code here:
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnPinKotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPinKotaActionPerformed
    String kota = txtCariNamaKota.getText();
    if (kota.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Nama kota tidak boleh kosong!", "Error", JOptionPane.ERROR_MESSAGE);
    } else {
        boolean isExist = false;
        for (int i = 0; i < cmbPilihKota.getItemCount(); i++) {
            if (cmbPilihKota.getItemAt(i).equalsIgnoreCase(kota)) {
                isExist = true;
                break;
            }
        }
        if (!isExist) {
            cmbPilihKota.addItem(kota);
            JOptionPane.showMessageDialog(this, "Kota berhasil ditambahkan ke daftar favorit!");

            // Simpan kota ke file
            try (FileWriter writer = new FileWriter("DataCuaca/kotaFavorit.txt", true)) { // 'true' untuk append
                writer.append(kota + "\n");
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Gagal menyimpan kota ke file: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Kota sudah ada di daftar favorit!", "Info", JOptionPane.INFORMATION_MESSAGE);
        }
    }    // TODO add your handling code here:
    }//GEN-LAST:event_btnPinKotaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplikasiCekCuacaSederhana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplikasiCekCuacaSederhana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplikasiCekCuacaSederhana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplikasiCekCuacaSederhana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplikasiCekCuacaSederhana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCekCuaca;
    private javax.swing.JButton btnMuatData;
    private javax.swing.JButton btnPinKota;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cmbPilihKota;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCuaca;
    private javax.swing.JLabel lblSuhu;
    private javax.swing.JTable tblDataCuaca;
    private javax.swing.JTextField txtCariNamaKota;
    // End of variables declaration//GEN-END:variables
}
